run_title: 'debug'

seed: 777

compute_infinite_width: True

n_experiments: 20

use_test_sample: True
n_test: 10000

# @package _global_
defaults:
  - location: local
  - hparams: default
  - target_function: hu_lu
  - activation: hu_lu
  - hydra: val_size_d
  - _self_
